export const CATEGORY_SUBS: Record<string, string[]> = {
  'Phones & Accessories': ['Mobile Phones', 'Tablets', 'Smart Watches', 'Headphones', 'Power Banks', 'Phone Cases', 'Chargers & Cables', 'Phone Accessories', 'Screen Protectors'],
  'Vehicles': ['Cars', 'Motorbikes', 'Trucks & Trailers', 'Buses & Microbuses', 'Vehicle Parts', 'Car Accessories', 'Tyres & Rims', 'Watercraft', 'Heavy Equipment'],
  'Property': ['Houses for Rent', 'Houses for Sale', 'Apartments', 'Land & Plots', 'Office Space', 'Warehouses', 'Commercial', 'Short Stay', 'Event Venues'],
  'Electronics': ['Laptops', 'Computers', 'TV & DVD', 'Audio & Music', 'Video Games', 'Cameras', 'Printers', 'Networking', 'Storage Devices'],
  'Home & Furniture': ['Furniture', 'Home Decor', 'Kitchen', 'Appliances', 'Bedding', 'Garden', 'Lighting', 'Storage', 'Bathroom'],
  'Fashion': ["Men's Wear", "Women's Wear", "Men's Shoes", "Women's Shoes", 'Bags', 'Watches', 'Jewelry', 'Kids Wear', 'Accessories'],
  'Beauty & Health': ['Makeup', 'Skin Care', 'Hair Care', 'Fragrances', 'Personal Care', 'Vitamins', 'Medical', 'Fitness', 'Health'],
  'Services': ['Automotive', 'IT Services', 'Cleaning', 'Events', 'Moving', 'Tours', 'Education', 'Business', 'Beauty Services'],
  'Sports & Leisure': ['Sports Gear', 'Gym Equipment', 'Instruments', 'Books', 'Bicycles', 'Camping', 'Toys', 'Art', 'Collectibles'],
  'Babies & Kids': ['Baby Clothing', 'Kids Clothing', 'Strollers', 'Toys', 'Baby Gear', 'Feeding', 'Bathing', 'Baby Shoes', 'Maternity'],
  'Agriculture': ['Farm Machinery', 'Livestock', 'Seeds', 'Crops', 'Poultry', 'Fish', 'Farm Tools', 'Fertilizers', 'Irrigation'],
  'Pets': ['Dogs', 'Cats', 'Birds', 'Fish', 'Pet Food', 'Pet Accessories', 'Grooming', 'Cages', 'Reptiles'],
  'Repair & Hardware': ['Building Materials', 'Plumbing', 'Electrical', 'Hand Tools', 'Power Tools', 'Roofing', 'Flooring', 'Painting', 'Hardware'],
  'Commercial & Office': ['Manufacturing', 'Restaurant Equipment', 'Store Equipment', 'Office Furniture', 'Medical Equipment', 'Salon Equipment', 'Printing', 'Stationery', 'Packaging'],
  'Jobs': ['Accounting', 'Admin & Secretarial', 'Engineering', 'Healthcare', 'IT & Tech', 'Marketing', 'Sales', 'Teaching', 'Hospitality'],
  'Food & Beverages': ['Groceries', 'Fresh Produce', 'Snacks & Confectionery', 'Beverages', 'Dairy & Eggs', 'Bakery', 'Meat & Poultry', 'Frozen Foods', 'Organic & Natural'],
  'Music & Instruments': ['Guitars', 'Keyboards & Pianos', 'Drums & Percussion', 'Wind Instruments', 'DJ Equipment', 'Studio Equipment', 'Microphones', 'Amplifiers', 'Music Accessories'],
  'Books & Stationery': ['Textbooks', 'Fiction & Literature', 'Business & Finance', 'Children Books', 'Magazines', 'Pens & Pencils', 'Notebooks', 'Art Supplies', 'Office Stationery'],
  'Gaming': ['Video Games', 'Gaming Consoles', 'Controllers & Joysticks', 'Gaming Chairs', 'Gaming Monitors', 'Headsets', 'Gaming PCs', 'VR Headsets', 'Gaming Accessories'],
  'Travel & Tourism': ['Flight Tickets', 'Hotel Bookings', 'Holiday Packages', 'Safari Tours', 'Car Hire', 'Travel Insurance', 'Cruise Packages', 'Adventure Activities', 'Travel Accessories'],
  'Healthcare': ['Medical Equipment', 'Wheelchairs & Mobility', 'Hearing Aids', 'Vision Care', 'Orthopaedic', 'Diagnostic Tools', 'Surgical Supplies', 'First Aid', 'Dental Care'],
  'Business & Investment': ['Business for Sale', 'Franchise Opportunities', 'Investment Opportunities', 'Tenders & Contracts', 'Business Equipment', 'Financial Services', 'Legal Services', 'Accounting Services', 'Consulting'],
  'Art & Crafts': ['Paintings', 'Sculptures', 'Photography', 'Handmade Jewelry', 'Pottery & Ceramics', 'Textile Art', 'Prints', 'Craft Supplies', 'Digital Art'],
};

export const CATEGORY_DATA_NAMES: Record<string, string | null> = {
  'Phones & Accessories': 'Phones',
  'Vehicles': 'Vehicles',
  'Property': null,
  'Electronics': 'Electronics',
  'Home & Furniture': 'Furniture',
  'Fashion': 'Fashion',
  'Beauty & Health': 'Beauty',
  'Services': 'Services',
  'Sports & Leisure': null,
  'Babies & Kids': null,
  'Agriculture': null,
  'Pets': null,
  'Repair & Hardware': null,
  'Commercial & Office': null,
  'Jobs': null,
  'Food & Beverages': null,
  'Music & Instruments': null,
  'Books & Stationery': null,
  'Gaming': null,
  'Travel & Tourism': null,
  'Healthcare': null,
  'Business & Investment': null,
  'Art & Crafts': null,
};
