import { Product, Category, Chat, FeedItem } from '../types';

export const categories: Category[] = [
  { id: 'all', name: 'All', icon: 'Grid', subcategories: [] },
  { id: 'vehicles', name: 'Vehicles', icon: 'Car', subcategories: ['Cars', 'Motorcycles', 'Trucks', 'Buses'] },
  { id: 'property', name: 'Property', icon: 'Home', subcategories: ['Houses', 'Apartments', 'Land', 'Commercial'] },
  { id: 'phones', name: 'Phones', icon: 'Smartphone', subcategories: ['iPhones', 'Samsung', 'Xiaomi', 'Accessories'] },
  { id: 'electronics', name: 'Electronics', icon: 'Monitor', subcategories: ['TVs', 'Laptops', 'Gaming', 'Audio'] },
  { id: 'furniture', name: 'Furniture', icon: 'Sofa', subcategories: ['Living Room', 'Bedroom', 'Office', 'Kitchen'] },
  { id: 'fashion', name: 'Fashion', icon: 'Shirt', subcategories: ['Men', 'Women', 'Kids', 'Shoes'] },
  { id: 'beauty', name: 'Beauty', icon: 'Sparkles', subcategories: ['Skincare', 'Makeup', 'Hair', 'Fragrance'] },
  { id: 'services', name: 'Services', icon: 'Wrench', subcategories: ['Plumbing', 'Electrical', 'Cleaning', 'Tutoring'] },
  { id: 'kids', name: 'Kids', icon: 'Baby', subcategories: ['Clothing', 'Toys', 'Baby Gear', 'School'] },
  { id: 'pets', name: 'Pets', icon: 'Cat', subcategories: ['Dogs', 'Cats', 'Birds', 'Supplies'] },
];

export const services = [
  { id: 's1', title: 'Professional Plumbing', location: 'Nairobi, Kenya', price: 'KSh 2,500', originalPrice: 'KSh 3,500', category: 'Services', likes: 45, rating: 4.8, reviews: '342', isOffer: true, discount: 29, offerExpiry: 3, description: 'Expert plumbing services for all your needs.', seller: { id: 'v1', name: 'John Kamau', avatar: 'J', rating: 4.8, verified: true } },
  { id: 's2', title: 'House Cleaning', location: 'Westlands, Nairobi', price: 'KSh 1,500', originalPrice: 'KSh 2,000', category: 'Services', likes: 32, rating: 4.6, reviews: '128', isOffer: true, discount: 25, offerExpiry: 5, description: 'Professional house cleaning services.', seller: { id: 'v2', name: 'Mary Wanjiku', avatar: 'M', rating: 4.6, verified: true } },
  { id: 's3', title: 'AC Repair & Service', location: 'Mombasa, Kenya', price: 'KSh 3,000', originalPrice: 'KSh 4,000', category: 'Services', likes: 67, rating: 4.9, reviews: '256', isOffer: true, discount: 25, offerExpiry: 2, description: 'Air conditioning repair and maintenance.', seller: { id: 'v3', name: 'Peter Ochieng', avatar: 'P', rating: 4.9, verified: true } },
  { id: 's4', title: 'Private Tutoring', location: 'Kisumu, Kenya', price: 'KSh 800', originalPrice: 'KSh 1,000', category: 'Services', likes: 28, rating: 4.7, reviews: '89', isOffer: true, discount: 20, offerExpiry: 4, description: 'One-on-one tutoring for all subjects.', seller: { id: 'v4', name: 'Jane Akinyi', avatar: 'J', rating: 4.7, verified: false } },
  { id: 's5', title: 'Event Photography', location: 'Nairobi, Kenya', price: 'KSh 15,000', originalPrice: 'KSh 20,000', category: 'Services', likes: 54, rating: 4.8, reviews: '198', isOffer: true, discount: 25, offerExpiry: 3, description: 'Professional photography for all events.', seller: { id: 'v5', name: 'David Mwangi', avatar: 'D', rating: 4.8, verified: true } },
  { id: 's6', title: 'Laptop Repair', location: 'Nairobi, Kenya', price: 'KSh 2,000', originalPrice: 'KSh 2,500', category: 'Services', likes: 89, rating: 4.5, reviews: '167', isOffer: true, discount: 20, offerExpiry: 6, description: 'Professional laptop repair. Screen, battery, motherboard.', seller: { id: 'v6', name: 'TechFix Solutions', avatar: 'T', rating: 4.6, verified: true } },
  { id: 's7', title: 'Car Wash & Detailing', location: 'Westlands, Nairobi', price: 'KSh 800', originalPrice: 'KSh 1,200', category: 'Services', likes: 234, rating: 4.7, reviews: '312', isOffer: true, discount: 33, offerExpiry: 4, description: 'Full car wash plus interior detailing. Premium service.', seller: { id: 'v7', name: 'Shine Auto', avatar: 'S', rating: 4.8, verified: true } },
  { id: 's8', title: 'Electrical Wiring', location: 'Nairobi, Kenya', price: 'KSh 3,500', originalPrice: 'KSh 4,500', category: 'Services', likes: 156, rating: 4.7, reviews: '234', isOffer: true, discount: 22, offerExpiry: 5, description: 'Professional electrical wiring. House, office, shops.', seller: { id: 'v8', name: 'PowerPro Electric', avatar: 'P', rating: 4.8, verified: true } },
  { id: 's9', title: 'Gardening & Landscaping', location: 'Karen, Nairobi', price: 'KSh 5,000', originalPrice: 'KSh 6,500', category: 'Services', likes: 78, rating: 4.6, reviews: '145', isOffer: true, discount: 23, offerExpiry: 3, description: 'Professional garden design and maintenance services.', seller: { id: 'v9', name: 'Green Gardens', avatar: 'G', rating: 4.7, verified: true } },
  { id: 's10', title: 'Mobile Phone Repair', location: 'Mombasa, Kenya', price: 'KSh 1,500', originalPrice: 'KSh 2,000', category: 'Services', likes: 312, rating: 4.8, reviews: '567', isOffer: true, discount: 25, offerExpiry: 2, description: 'Screen replacement, battery, water damage repair.', seller: { id: 'v10', name: 'FixIt Mobile', avatar: 'F', rating: 4.9, verified: true } },
  { id: 's11', title: 'Carpentry Services', location: 'Kisumu, Kenya', price: 'KSh 2,800', originalPrice: 'KSh 3,500', category: 'Services', likes: 67, rating: 4.5, reviews: '89', isOffer: true, discount: 20, offerExpiry: 7, description: 'Custom furniture, repairs, and woodwork services.', seller: { id: 'v11', name: 'WoodCraft Pro', avatar: 'W', rating: 4.6, verified: true } },
  { id: 's12', title: 'Massage Therapy', location: 'Nairobi, Kenya', price: 'KSh 2,200', originalPrice: 'KSh 3,000', category: 'Services', likes: 145, rating: 4.9, reviews: '278', isOffer: true, discount: 27, offerExpiry: 4, description: 'Professional massage therapy at your home or office.', seller: { id: 'v12', name: 'Relax Spa', avatar: 'R', rating: 4.9, verified: true } },
  { id: 's13', title: 'Pest Control', location: 'Nairobi, Kenya', price: 'KSh 3,000', originalPrice: 'KSh 4,000', category: 'Services', likes: 89, rating: 4.6, reviews: '156', isOffer: true, discount: 25, offerExpiry: 5, description: 'Complete pest control for homes and businesses.', seller: { id: 'v13', name: 'PestFree KE', avatar: 'P', rating: 4.7, verified: true } },
  { id: 's14', title: 'Home Security Installation', location: 'Nairobi, Kenya', price: 'KSh 8,500', originalPrice: 'KSh 12,000', category: 'Services', likes: 56, rating: 4.8, reviews: '123', isOffer: true, discount: 29, offerExpiry: 3, description: 'CCTV, alarm systems, and smart home security setup.', seller: { id: 'v14', name: 'SecureHome', avatar: 'S', rating: 4.8, verified: true } },
  { id: 's15', title: 'Pool Cleaning', location: 'Mombasa, Kenya', price: 'KSh 4,500', originalPrice: 'KSh 6,000', category: 'Services', likes: 34, rating: 4.7, reviews: '67', isOffer: true, discount: 25, offerExpiry: 6, description: 'Weekly pool maintenance and cleaning services.', seller: { id: 'v15', name: 'Blue Pools', avatar: 'B', rating: 4.7, verified: true } },
];

export const secondaryBanners = [
  { id: 1, title: 'FLASH DEALS', subtitle: 'Limited Time Only', description: 'Up to 70% Off', badge: 'LIVE', gradient: 'from-purple-700 to-purple-400' },
  { id: 2, title: 'TOP SELLERS', subtitle: 'Most Popular Items', description: 'Trending Now', badge: 'TOP', gradient: 'from-orange-600 to-amber-400' },
  { id: 3, title: 'NEW ARRIVALS', subtitle: 'Fresh Products Daily', description: 'Just Landed', badge: 'NEW', gradient: 'from-cyan-700 to-cyan-400' },
];

export const promoTips = [
  { id: 1, title: 'Boost Your Rankings', description: 'Learn how to rank higher in AOS search results', link: '/tips/ranking', color: 'from-blue-600 to-indigo-600' },
  { id: 2, title: 'Marketing Tips', description: 'Grow your sales with proven marketing strategies', link: '/tips/marketing', color: 'from-green-600 to-emerald-500' },
  { id: 3, title: 'Photography Tips', description: 'Take stunning product photos that sell', link: '/tips/photography', color: 'from-pink-600 to-rose-500' },
];

export const products: Product[] = [
  {
    id: '1',
    title: 'Toyota Axio 2015',
    location: 'Nairobi, Kenya',
    price: 'Ksh 1,450,000',
    originalPrice: 'Ksh 1,650,000',
    category: 'Vehicles',
    likes: 342,
    rating: 4.5,
    reviews: '1.4K',
    isOffer: true,
    discount: 12,
    offerExpiry: 14,
    description: 'Well maintained Toyota Axio 2015 model. Low mileage, fully serviced.',
    seller: { id: '1', name: 'AutoMart Kenya', avatar: 'A', rating: 4.8, verified: true },
  },
  {
    id: '2',
    title: 'iPhone 14 Pro Max',
    location: 'Mombasa, Kenya',
    price: 'Ksh 145,000',
    originalPrice: 'Ksh 165,000',
    category: 'Phones',
    likes: 521,
    rating: 4.8,
    reviews: '2.1K',
    isOffer: true,
    discount: 12,
    offerExpiry: 5,
    description: 'Brand new iPhone 14 Pro Max 256GB. Sealed box with warranty.',
    seller: { id: '2', name: 'TechHub', avatar: 'T', rating: 4.9, verified: true },
  },
  {
    id: '3',
    title: 'Samsung 55" Smart TV',
    location: 'Kisumu, Kenya',
    price: 'Ksh 65,000',
    originalPrice: 'Ksh 78,000',
    category: 'Electronics',
    likes: 289,
    rating: 4.3,
    reviews: '890',
    isOffer: true,
    discount: 17,
    offerExpiry: 3,
    description: 'Crystal UHD 4K Smart TV with built-in apps.',
    seller: { id: '3', name: 'ElectroWorld', avatar: 'E', rating: 4.6, verified: true },
  },
  {
    id: '4',
    title: 'MacBook Pro M2',
    location: 'Nairobi, Kenya',
    price: 'Ksh 185,000',
    category: 'Electronics',
    likes: 478,
    rating: 4.9,
    reviews: '1.8K',
    isOffer: false,
    description: 'MacBook Pro 14" M2 chip, 16GB RAM, 512GB SSD.',
    seller: { id: '4', name: 'Apple Store KE', avatar: 'A', rating: 4.9, verified: true },
  },
  {
    id: '5',
    title: 'Modern Leather Sofa Set',
    location: 'Nairobi, Kenya',
    price: 'Ksh 95,000',
    originalPrice: 'Ksh 120,000',
    category: 'Furniture',
    likes: 156,
    rating: 4.4,
    reviews: '420',
    isOffer: true,
    discount: 21,
    offerExpiry: 7,
    description: '3+2+1 seater genuine leather sofa set. Available for pickup or negotiate with seller.',
    seller: { id: '5', name: 'Furniture Palace', avatar: 'F', rating: 4.5, verified: true },
  },
  {
    id: '6',
    title: 'PlayStation 5 Console',
    location: 'Nairobi, Kenya',
    price: 'Ksh 72,000',
    originalPrice: 'Ksh 85,000',
    category: 'Electronics',
    likes: 892,
    rating: 4.9,
    reviews: '3.2K',
    isOffer: true,
    discount: 15,
    offerExpiry: 2,
    description: 'PS5 Disc Edition with 2 controllers.',
    seller: { id: '6', name: 'GameZone', avatar: 'G', rating: 4.8, verified: true },
  },
  {
    id: '7',
    title: 'Nike Air Jordan 1',
    location: 'Mombasa, Kenya',
    price: 'Ksh 8,500',
    category: 'Fashion',
    likes: 234,
    rating: 4.6,
    reviews: '180',
    isOffer: false,
    description: 'Authentic Nike Air Jordan 1 High. Size 9-12 available.',
    seller: { id: '7', name: 'SneakerHead KE', avatar: 'S', rating: 4.7, verified: false },
  },
  {
    id: '8',
    title: 'Washing Machine - 7kg',
    location: 'Kisumu, Kenya',
    price: 'Ksh 38,000',
    originalPrice: 'Ksh 45,000',
    category: 'Electronics',
    likes: 167,
    rating: 4.2,
    reviews: '95',
    isOffer: true,
    discount: 16,
    offerExpiry: 10,
    description: 'LG 7kg Front Load Washing Machine. Energy efficient.',
    seller: { id: '8', name: 'Home Appliances', avatar: 'H', rating: 4.3, verified: true },
  },
  {
    id: '9',
    title: 'House Cleaning Service',
    location: 'Nairobi, Kenya',
    price: 'Ksh 2,500',
    category: 'Services',
    likes: 89,
    rating: 4.7,
    reviews: '156',
    isOffer: false,
    description: 'Professional house cleaning. Per session pricing.',
    seller: { id: '9', name: 'CleanPro', avatar: 'C', rating: 4.8, verified: true },
  },
  {
    id: '10',
    title: 'Kids Bicycle 16"',
    location: 'Nairobi, Kenya',
    price: 'Ksh 7,800',
    originalPrice: 'Ksh 9,500',
    category: 'Kids',
    likes: 145,
    rating: 4.5,
    reviews: '78',
    isOffer: true,
    discount: 18,
    offerExpiry: 5,
    description: 'BMX style kids bike with training wheels. Ages 4-7.',
    seller: { id: '10', name: 'Toys R Us', avatar: 'T', rating: 4.6, verified: true },
  },
  {
    id: '11',
    title: 'Gaming Laptop RTX 4060',
    location: 'Nairobi, Kenya',
    price: 'Ksh 125,000',
    originalPrice: 'Ksh 145,000',
    category: 'Electronics',
    likes: 567,
    rating: 4.8,
    reviews: '890',
    isOffer: true,
    discount: 14,
    offerExpiry: 4,
    description: 'ASUS TUF Gaming F15. i7, 16GB RAM, RTX 4060.',
    seller: { id: '11', name: 'TechDeals', avatar: 'T', rating: 4.9, verified: true },
  },
  {
    id: '12',
    title: 'Designer Handbag',
    location: 'Mombasa, Kenya',
    price: 'Ksh 12,500',
    category: 'Fashion',
    likes: 234,
    rating: 4.4,
    reviews: '67',
    isOffer: false,
    description: 'Authentic designer handbag. Limited edition.',
    seller: { id: '12', name: 'Luxury Bags', avatar: 'L', rating: 4.5, verified: false },
  },
  { id: '13', title: 'Dining Table Set', location: 'Nairobi, Kenya', price: 'Ksh 42,000', originalPrice: 'Ksh 55,000', category: 'Furniture', likes: 98, rating: 4.3, reviews: '45', isOffer: true, discount: 24, offerExpiry: 6, description: '6-seater dining table with chairs. Solid wood.', seller: { id: '13', name: 'Furniture Palace', avatar: 'F', rating: 4.5, verified: true } },
  { id: '14', title: 'Office Desk & Chair', location: 'Nairobi, Kenya', price: 'Ksh 25,000', originalPrice: 'Ksh 32,000', category: 'Furniture', likes: 134, rating: 4.4, reviews: '112', isOffer: true, discount: 22, offerExpiry: 7, description: 'Executive office desk with ergonomic chair.', seller: { id: '14', name: 'Office World', avatar: 'O', rating: 4.6, verified: true } },
  { id: '15', title: 'Bed Frame Queen', location: 'Kisumu, Kenya', price: 'Ksh 35,000', category: 'Furniture', likes: 78, rating: 4.2, reviews: '34', isOffer: false, description: 'Solid wood queen bed frame. Modern design.', seller: { id: '15', name: 'Sleep Haven', avatar: 'S', rating: 4.3, verified: true } },
  { id: '16', title: 'Wardrobe 3-Door', location: 'Nakuru, Kenya', price: 'Ksh 55,000', category: 'Furniture', likes: 67, rating: 4.1, reviews: '28', isOffer: false, description: 'Large 3-door wardrobe with mirror.', seller: { id: '15', name: 'Sleep Haven', avatar: 'S', rating: 4.3, verified: true } },
  { id: '17', title: 'Kitchen Cabinet Set', location: 'Mombasa, Kenya', price: 'Ksh 28,000', category: 'Furniture', likes: 56, rating: 4.0, reviews: '19', isOffer: false, description: 'Modern kitchen cabinet with granite top.', seller: { id: '13', name: 'Furniture Palace', avatar: 'F', rating: 4.5, verified: true } },
  { id: '18', title: 'Sony Headphones WH-1000XM5', location: 'Nairobi, Kenya', price: 'Ksh 32,000', originalPrice: 'Ksh 42,000', category: 'Electronics', likes: 445, rating: 4.7, reviews: '890', isOffer: true, discount: 24, offerExpiry: 3, description: 'Premium noise cancelling wireless headphones.', seller: { id: '6', name: 'GameZone', avatar: 'G', rating: 4.8, verified: true } },
  { id: '19', title: 'iPad Air M1', location: 'Thika, Kenya', price: 'Ksh 75,000', originalPrice: 'Ksh 89,000', category: 'Electronics', likes: 312, rating: 4.8, reviews: '456', isOffer: true, discount: 16, offerExpiry: 5, description: 'iPad Air with M1 chip. 256GB WiFi.', seller: { id: '4', name: 'Apple Store KE', avatar: 'A', rating: 4.9, verified: true } },
  { id: '20', title: 'Canon EOS R50 Camera', location: 'Nairobi, Kenya', price: 'Ksh 95,000', originalPrice: 'Ksh 115,000', category: 'Electronics', likes: 189, rating: 4.6, reviews: '78', isOffer: true, discount: 17, offerExpiry: 4, description: 'Mirrorless camera with 18-45mm lens kit.', seller: { id: '11', name: 'TechDeals', avatar: 'T', rating: 4.9, verified: true } },
  { id: '21', title: "Men's Suit Set", location: 'Mombasa, Kenya', price: 'Ksh 15,000', category: 'Fashion', likes: 145, rating: 4.5, reviews: '89', isOffer: false, description: 'Slim fit 3-piece suit. Multiple colors available.', seller: { id: '21', name: 'Style Hub', avatar: 'S', rating: 4.4, verified: true } },
  { id: '22', title: 'Designer Dress', location: 'Nairobi, Kenya', price: 'Ksh 8,500', originalPrice: 'Ksh 12,000', category: 'Fashion', likes: 267, rating: 4.6, reviews: '156', isOffer: true, discount: 29, offerExpiry: 3, description: 'Elegant evening dress. Premium fabric.', seller: { id: '22', name: 'FashionHouse', avatar: 'F', rating: 4.7, verified: true } },
  { id: '23', title: 'Sneakers Nike Air', location: 'Nairobi, Kenya', price: 'Ksh 12,000', category: 'Fashion', likes: 345, rating: 4.7, reviews: '234', isOffer: false, description: 'Nike Air Max 90. All sizes available.', seller: { id: '7', name: 'SneakerHead KE', avatar: 'S', rating: 4.7, verified: false } },
  { id: '24', title: 'Leather Jacket', location: 'Nairobi, Kenya', price: 'Ksh 6,500', category: 'Fashion', likes: 178, rating: 4.3, reviews: '67', isOffer: false, description: 'Genuine leather biker jacket. Unisex.', seller: { id: '21', name: 'Style Hub', avatar: 'S', rating: 4.4, verified: true } },
  { id: '25', title: 'Skincare Gift Set', location: 'Nairobi, Kenya', price: 'Ksh 4,500', originalPrice: 'Ksh 6,000', category: 'Beauty', likes: 312, rating: 4.8, reviews: '234', isOffer: true, discount: 25, offerExpiry: 2, description: 'Complete skincare routine set. Korean beauty.', seller: { id: '25', name: 'GlowUp Beauty', avatar: 'G', rating: 4.9, verified: true } },
  { id: '26', title: 'Perfume Collection', location: 'Mombasa, Kenya', price: 'Ksh 3,800', category: 'Beauty', likes: 189, rating: 4.5, reviews: '145', isOffer: false, description: 'Set of 3 premium fragrances. Long lasting.', seller: { id: '25', name: 'GlowUp Beauty', avatar: 'G', rating: 4.9, verified: true } },
  { id: '27', title: 'Hair Extensions Bundle', location: 'Nairobi, Kenya', price: 'Ksh 5,200', category: 'Beauty', likes: 234, rating: 4.4, reviews: '178', isOffer: false, description: '100% human hair. Brazilian body wave.', seller: { id: '27', name: 'Hair Studio', avatar: 'H', rating: 4.6, verified: true } },
  { id: '28', title: 'Makeup Kit Pro', location: 'Nairobi, Kenya', price: 'Ksh 7,500', originalPrice: 'Ksh 9,000', category: 'Beauty', likes: 156, rating: 4.6, reviews: '89', isOffer: true, discount: 17, offerExpiry: 5, description: 'Professional makeup kit with brushes.', seller: { id: '25', name: 'GlowUp Beauty', avatar: 'G', rating: 4.9, verified: true } },
  { id: '29', title: 'Baby Stroller Deluxe', location: 'Nairobi, Kenya', price: 'Ksh 18,000', originalPrice: 'Ksh 22,000', category: 'Kids', likes: 89, rating: 4.5, reviews: '56', isOffer: true, discount: 18, offerExpiry: 4, description: 'Foldable stroller with car seat. 0-3 years.', seller: { id: '29', name: 'Baby World', avatar: 'B', rating: 4.7, verified: true } },
  { id: '30', title: 'Kids School Bag Set', location: 'Nairobi, Kenya', price: 'Ksh 3,500', category: 'Kids', likes: 145, rating: 4.3, reviews: '89', isOffer: false, description: 'Backpack + lunch box + water bottle set.', seller: { id: '29', name: 'Baby World', avatar: 'B', rating: 4.7, verified: true } },
  { id: '31', title: 'Lego Building Set', location: 'Mombasa, Kenya', price: 'Ksh 4,200', category: 'Kids', likes: 234, rating: 4.8, reviews: '167', isOffer: false, description: '500+ pieces creative building set. Ages 6+.', seller: { id: '10', name: 'Toys R Us', avatar: 'T', rating: 4.6, verified: true } },
  { id: '32', title: "Children's Clothing Bundle", location: 'Kisumu, Kenya', price: 'Ksh 2,800', originalPrice: 'Ksh 4,000', category: 'Kids', likes: 67, rating: 4.2, reviews: '34', isOffer: true, discount: 30, offerExpiry: 6, description: '5-piece clothing set. Ages 2-5.', seller: { id: '29', name: 'Baby World', avatar: 'B', rating: 4.7, verified: true } },
  { id: '33', title: '3 Bedroom Apartment', location: 'Westlands, Nairobi', price: 'Ksh 45,000/mo', category: 'Property', likes: 456, rating: 4.6, reviews: '89', isOffer: false, description: 'Spacious 3BR apartment. Master ensuite. 24hr security.', seller: { id: '33', name: 'Prime Realtors', avatar: 'P', rating: 4.8, verified: true } },
  { id: '34', title: 'Honda CRV 2018', location: 'Eldoret, Kenya', price: 'Ksh 2,800,000', originalPrice: 'Ksh 3,100,000', category: 'Vehicles', likes: 234, rating: 4.5, reviews: '67', isOffer: true, discount: 10, offerExpiry: 2, description: 'Low mileage, leather interior, sunroof.', seller: { id: '1', name: 'AutoMart Kenya', avatar: 'A', rating: 4.8, verified: true } },
  { id: '35', title: 'Samsung Galaxy S24', location: 'Thika, Kenya', price: 'Ksh 125,000', originalPrice: 'Ksh 140,000', category: 'Phones', likes: 567, rating: 4.8, reviews: '345', isOffer: true, discount: 11, offerExpiry: 3, description: 'Samsung Galaxy S24 Ultra. 512GB. New sealed.', seller: { id: '2', name: 'TechHub', avatar: 'T', rating: 4.9, verified: true } },
  // Additional products to fill categories
  { id: '36', title: 'Golden Retriever Puppy', location: 'Nairobi, Kenya', price: 'Ksh 25,000', category: 'Pets', likes: 89, rating: 4.9, reviews: '45', isOffer: false, description: 'Purebred Golden Retriever puppy. 8 weeks old. Vaccinated.', seller: { id: '36', name: 'Pet Haven', avatar: 'P', rating: 4.8, verified: true } },
  { id: '37', title: 'Persian Cat', location: 'Mombasa, Kenya', price: 'Ksh 18,000', originalPrice: 'Ksh 22,000', category: 'Pets', likes: 67, rating: 4.7, reviews: '34', isOffer: true, discount: 18, offerExpiry: 5, description: 'Beautiful Persian cat. 1 year old. All shots up to date.', seller: { id: '37', name: 'Cats & Co', avatar: 'C', rating: 4.6, verified: true } },
  { id: '38', title: 'Parrot with Cage', location: 'Kisumu, Kenya', price: 'Ksh 8,500', category: 'Pets', likes: 45, rating: 4.5, reviews: '23', isOffer: false, description: 'Talking parrot with large cage. 3 years old.', seller: { id: '36', name: 'Pet Haven', avatar: 'P', rating: 4.8, verified: true } },
  { id: '39', title: 'German Shepherd Puppy', location: 'Nakuru, Kenya', price: 'Ksh 20,000', category: 'Pets', likes: 112, rating: 4.8, reviews: '56', isOffer: false, description: 'Healthy German Shepherd puppy. Trained, vaccinated.', seller: { id: '39', name: 'K9 World', avatar: 'K', rating: 4.9, verified: true } },
  { id: '40', title: 'Fish Aquarium Set', location: 'Nairobi, Kenya', price: 'Ksh 12,000', originalPrice: 'Ksh 15,000', category: 'Pets', likes: 34, rating: 4.3, reviews: '18', isOffer: true, discount: 20, offerExpiry: 4, description: '50L aquarium with filter, heater and decorations.', seller: { id: '36', name: 'Pet Haven', avatar: 'P', rating: 4.8, verified: true } },
  { id: '41', title: '4 Bedroom Villa', location: 'Karen, Nairobi', price: 'Ksh 85,000/mo', category: 'Property', likes: 234, rating: 4.7, reviews: '45', isOffer: false, description: 'Luxury 4BR villa with garden and parking. All ensuite.', seller: { id: '41', name: 'Luxury Homes', avatar: 'L', rating: 4.9, verified: true } },
  { id: '42', title: 'Studio Apartment', location: 'Kilimani, Nairobi', price: 'Ksh 25,000/mo', originalPrice: 'Ksh 30,000/mo', category: 'Property', likes: 156, rating: 4.4, reviews: '67', isOffer: true, discount: 17, offerExpiry: 3, description: 'Modern studio apartment. Furnished option available.', seller: { id: '33', name: 'Prime Realtors', avatar: 'P', rating: 4.8, verified: true } },
  { id: '43', title: 'Commercial Shop', location: 'CBD, Nairobi', price: 'Ksh 35,000/mo', category: 'Property', likes: 78, rating: 4.2, reviews: '29', isOffer: false, description: 'Ground floor shop. High foot traffic area. Ready for business.', seller: { id: '43', name: 'BizSpace KE', avatar: 'B', rating: 4.5, verified: true } },
  { id: '44', title: 'Land for Sale - 1 Acre', location: 'Kiambu, Kenya', price: 'Ksh 4,500,000', category: 'Property', likes: 189, rating: 4.6, reviews: '34', isOffer: false, description: 'Prime 1-acre plot. Ready title deed. Good for residential.', seller: { id: '44', name: 'Land Masters', avatar: 'L', rating: 4.7, verified: true } },
  { id: '45', title: 'Mazda CX-5 2020', location: 'Nairobi, Kenya', price: 'Ksh 3,200,000', originalPrice: 'Ksh 3,600,000', category: 'Vehicles', likes: 345, rating: 4.7, reviews: '89', isOffer: true, discount: 11, offerExpiry: 4, description: 'Mazda CX-5 AWD. Low mileage. Sunroof, leather seats.', seller: { id: '1', name: 'AutoMart Kenya', avatar: 'A', rating: 4.8, verified: true } },
  { id: '46', title: 'Subaru Forester 2019', location: 'Nakuru, Kenya', price: 'Ksh 2,450,000', category: 'Vehicles', likes: 267, rating: 4.6, reviews: '78', isOffer: false, description: 'Subaru Forester XT Turbo. EyeSight system. AWD.', seller: { id: '46', name: 'Subaru Specialists', avatar: 'S', rating: 4.7, verified: true } },
  { id: '47', title: 'Yamaha R3 Motorcycle', location: 'Mombasa, Kenya', price: 'Ksh 450,000', originalPrice: 'Ksh 520,000', category: 'Vehicles', likes: 156, rating: 4.8, reviews: '45', isOffer: true, discount: 13, offerExpiry: 2, description: 'Yamaha YZF-R3. 321cc. Sports bike. Low mileage.', seller: { id: '47', name: 'MotoWorld', avatar: 'M', rating: 4.8, verified: true } },
  { id: '48', title: 'iPhone 15 Pro Max', location: 'Nairobi, Kenya', price: 'Ksh 185,000', category: 'Phones', likes: 789, rating: 4.9, reviews: '567', isOffer: false, description: 'iPhone 15 Pro Max 256GB. Natural Titanium. Sealed.', seller: { id: '4', name: 'Apple Store KE', avatar: 'A', rating: 4.9, verified: true } },
  { id: '49', title: 'Google Pixel 8 Pro', location: 'Nairobi, Kenya', price: 'Ksh 115,000', originalPrice: 'Ksh 135,000', category: 'Phones', likes: 234, rating: 4.7, reviews: '123', isOffer: true, discount: 15, offerExpiry: 5, description: 'Google Pixel 8 Pro. 128GB. Best camera phone.', seller: { id: '2', name: 'TechHub', avatar: 'T', rating: 4.9, verified: true } },
  { id: '50', title: 'Xiaomi 14 Ultra', location: 'Mombasa, Kenya', price: 'Ksh 95,000', category: 'Phones', likes: 178, rating: 4.6, reviews: '89', isOffer: false, description: 'Xiaomi 14 Ultra. Leica camera. 512GB storage.', seller: { id: '50', name: 'Xiaomi Store', avatar: 'X', rating: 4.5, verified: true } },
  { id: '51', title: 'Plumbing Repair Service', location: 'Nairobi, Kenya', price: 'Ksh 1,500', category: 'Services', likes: 123, rating: 4.8, reviews: '234', isOffer: false, description: 'Expert plumbing repairs. Leak fixing, pipe replacement.', seller: { id: '51', name: 'PlumbPro', avatar: 'P', rating: 4.9, verified: true } },
  { id: '52', title: 'Laptop Repair', location: 'Nairobi, Kenya', price: 'Ksh 2,000', category: 'Services', likes: 89, rating: 4.5, reviews: '67', isOffer: false, description: 'Professional laptop repair. Screen, battery, motherboard.', seller: { id: '52', name: 'TechFix', avatar: 'T', rating: 4.6, verified: true } },
  { id: '53', title: 'Car Wash & Detailing', location: 'Westlands, Nairobi', price: 'Ksh 800', originalPrice: 'Ksh 1,200', category: 'Services', likes: 234, rating: 4.7, reviews: '156', isOffer: true, discount: 33, offerExpiry: 7, description: 'Full car wash plus interior detailing. Premium service.', seller: { id: '53', name: 'Shine Auto', avatar: 'S', rating: 4.8, verified: true } },
  { id: '54', title: 'iPhone 13 Pro', location: 'Kisumu, Kenya', price: 'Ksh 95,000', originalPrice: 'Ksh 115,000', category: 'Phones', likes: 456, rating: 4.8, reviews: '234', isOffer: true, discount: 17, offerExpiry: 3, description: 'iPhone 13 Pro 128GB. Sierra Blue. Excellent condition.', seller: { id: '54', name: 'Phone Hub', avatar: 'P', rating: 4.7, verified: true } },
  { id: '55', title: 'Samsung Fold 5', location: 'Nairobi, Kenya', price: 'Ksh 165,000', category: 'Phones', likes: 312, rating: 4.6, reviews: '89', isOffer: false, description: 'Samsung Galaxy Z Fold 5. 256GB. Phantom Black.', seller: { id: '2', name: 'TechHub', avatar: 'T', rating: 4.9, verified: true } },
  { id: '56', title: 'DJI Drone Mini 3', location: 'Nairobi, Kenya', price: 'Ksh 65,000', originalPrice: 'Ksh 78,000', category: 'Electronics', likes: 234, rating: 4.8, reviews: '123', isOffer: true, discount: 17, offerExpiry: 4, description: 'DJI Mini 3 drone. 4K camera. 38min flight time.', seller: { id: '11', name: 'TechDeals', avatar: 'T', rating: 4.9, verified: true } },
  { id: '57', title: 'Electric Kettle', location: 'Nairobi, Kenya', price: 'Ksh 2,500', category: 'Electronics', likes: 45, rating: 4.2, reviews: '67', isOffer: false, description: '1.7L stainless steel kettle. Fast boil. Auto shut-off.', seller: { id: '3', name: 'ElectroWorld', avatar: 'E', rating: 4.6, verified: true } },
  { id: '58', title: 'Smart Watch Series 9', location: 'Mombasa, Kenya', price: 'Ksh 45,000', originalPrice: 'Ksh 55,000', category: 'Electronics', likes: 189, rating: 4.7, reviews: '234', isOffer: true, discount: 18, offerExpiry: 5, description: 'Apple Watch Series 9. GPS + Cellular. 45mm.', seller: { id: '4', name: 'Apple Store KE', avatar: 'A', rating: 4.9, verified: true } },
  { id: '59', title: 'Coffee Table', location: 'Nairobi, Kenya', price: 'Ksh 8,500', category: 'Furniture', likes: 78, rating: 4.3, reviews: '45', isOffer: false, description: 'Modern glass coffee table. Chrome legs. Elegant design.', seller: { id: '13', name: 'Furniture Palace', avatar: 'F', rating: 4.5, verified: true } },
  { id: '60', title: 'Bookshelf', location: 'Nairobi, Kenya', price: 'Ksh 12,000', originalPrice: 'Ksh 15,000', category: 'Furniture', likes: 56, rating: 4.1, reviews: '34', isOffer: true, discount: 20, offerExpiry: 6, description: '5-tier wooden bookshelf. Adjustable shelves. White.', seller: { id: '13', name: 'Furniture Palace', avatar: 'F', rating: 4.5, verified: true } },
  { id: '61', title: 'Women Handbag Set', location: 'Nairobi, Kenya', price: 'Ksh 4,500', category: 'Fashion', likes: 189, rating: 4.5, reviews: '123', isOffer: false, description: '3-piece handbag set. Tote, clutch, and wallet. PU leather.', seller: { id: '22', name: 'FashionHouse', avatar: 'F', rating: 4.7, verified: true } },
  { id: '62', title: 'Men Running Shoes', location: 'Mombasa, Kenya', price: 'Ksh 5,800', originalPrice: 'Ksh 7,200', category: 'Fashion', likes: 234, rating: 4.6, reviews: '89', isOffer: true, discount: 19, offerExpiry: 3, description: 'Adidas Ultraboost running shoes. Size 7-11. Black.', seller: { id: '7', name: 'SneakerHead KE', avatar: 'S', rating: 4.7, verified: false } },
  { id: '63', title: 'Face Serum', location: 'Nairobi, Kenya', price: 'Ksh 1,800', category: 'Beauty', likes: 123, rating: 4.7, reviews: '67', isOffer: false, description: 'Vitamin C face serum. Brightening formula. 30ml.', seller: { id: '25', name: 'GlowUp Beauty', avatar: 'G', rating: 4.9, verified: true } },
  { id: '64', title: 'Nail Polish Set', location: 'Nairobi, Kenya', price: 'Ksh 1,200', originalPrice: 'Ksh 1,800', category: 'Beauty', likes: 67, rating: 4.4, reviews: '45', isOffer: true, discount: 33, offerExpiry: 5, description: '12 colors nail polish set. Long lasting. Gel finish.', seller: { id: '25', name: 'GlowUp Beauty', avatar: 'G', rating: 4.9, verified: true } },
  { id: '65', title: 'Baby Crib', location: 'Nairobi, Kenya', price: 'Ksh 22,000', category: 'Kids', likes: 89, rating: 4.6, reviews: '56', isOffer: false, description: 'Convertible baby crib. 3 height levels. White wood.', seller: { id: '29', name: 'Baby World', avatar: 'B', rating: 4.7, verified: true } },
  { id: '66', title: 'Kids Tablet', location: 'Nairobi, Kenya', price: 'Ksh 8,500', originalPrice: 'Ksh 12,000', category: 'Kids', likes: 156, rating: 4.5, reviews: '78', isOffer: true, discount: 29, offerExpiry: 4, description: 'Educational kids tablet. Pre-loaded learning apps. 32GB.', seller: { id: '10', name: 'Toys R Us', avatar: 'T', rating: 4.6, verified: true } },
  { id: '67', title: 'Toy Car Remote', location: 'Mombasa, Kenya', price: 'Ksh 3,200', category: 'Kids', likes: 234, rating: 4.8, reviews: '123', isOffer: false, description: 'Remote control car. Rechargeable. 2.4GHz. 1:16 scale.', seller: { id: '10', name: 'Toys R Us', avatar: 'T', rating: 4.6, verified: true } },
  { id: '68', title: 'Cat Food - 5kg', location: 'Nairobi, Kenya', price: 'Ksh 2,500', category: 'Pets', likes: 45, rating: 4.5, reviews: '34', isOffer: false, description: 'Premium dry cat food. Complete nutrition. Tuna flavor.', seller: { id: '36', name: 'Pet Haven', avatar: 'P', rating: 4.8, verified: true } },
  { id: '69', title: 'Dog Bed Large', location: 'Nairobi, Kenya', price: 'Ksh 3,800', originalPrice: 'Ksh 4,800', category: 'Pets', likes: 78, rating: 4.6, reviews: '45', isOffer: true, discount: 21, offerExpiry: 6, description: 'Orthopedic memory foam dog bed. Removable cover. XL.', seller: { id: '36', name: 'Pet Haven', avatar: 'P', rating: 4.8, verified: true } },
  { id: '70', title: 'Electrical Wiring Service', location: 'Nairobi, Kenya', price: 'Ksh 3,500', category: 'Services', likes: 156, rating: 4.7, reviews: '89', isOffer: false, description: 'Professional electrical wiring. House, office, shops.', seller: { id: '70', name: 'PowerPro', avatar: 'P', rating: 4.8, verified: true } },
];

export const chats: Chat[] = [
  {
    id: '1',
    name: 'AutoMart Kenya',
    avatar: 'A',
    online: true,
    lastMessage: 'Is the car still available?',
    timestamp: '2m ago',
    unread: 2,
    messages: [
      { id: '1', sender: 'other', text: 'Hello! How can I help you today?', timestamp: '10:00 AM' },
      { id: '2', sender: 'user', text: 'Hi, I saw the Toyota Axio listing', timestamp: '10:05 AM' },
      { id: '3', sender: 'other', text: 'Yes, it is still available!', timestamp: '10:06 AM' },
      { id: '4', sender: 'user', text: 'Is the car still available?', timestamp: '10:30 AM' },
    ],
  },
  {
    id: '2',
    name: 'TechHub',
    avatar: 'T',
    online: false,
    lastMessage: 'The iPhone comes with warranty',
    timestamp: '1h ago',
    unread: 0,
    messages: [
      { id: '1', sender: 'other', text: 'Thank you for your interest!', timestamp: '9:00 AM' },
      { id: '2', sender: 'other', text: 'The iPhone comes with warranty', timestamp: '9:01 AM' },
    ],
  },
  {
    id: '3',
    name: 'Furniture Palace',
    avatar: 'F',
    online: true,
    lastMessage: 'Feel free to negotiate the price',
    timestamp: '3h ago',
    unread: 1,
    messages: [
      { id: '1', sender: 'user', text: 'Is the price negotiable?', timestamp: '8:00 AM' },
      { id: '2', sender: 'other', text: 'Feel free to negotiate the price', timestamp: '8:15 AM' },
    ],
  },
  {
    id: '4',
    name: 'Nairobi Electronics',
    avatar: 'N',
    online: false,
    lastMessage: 'We have restocked the Samsung Galaxy.',
    timestamp: 'Yesterday',
    unread: 2,
    messages: [
      { id: '1', sender: 'other', text: 'We have restocked the Samsung Galaxy.', timestamp: 'Yesterday' },
    ],
  },
  {
    id: '5',
    name: 'Jane Mwangi',
    avatar: 'J',
    online: true,
    lastMessage: 'I can do Ksh 140,000 for the MacBook.',
    timestamp: '9:45 AM',
    unread: 1,
    messages: [
      { id: '1', sender: 'other', text: 'Hi! Interested in the MacBook?', timestamp: '9:30 AM' },
      { id: '2', sender: 'user', text: 'Yes — what is your best price?', timestamp: '9:40 AM' },
      { id: '3', sender: 'other', text: 'I can do Ksh 140,000 for the MacBook.', timestamp: '9:45 AM' },
    ],
  },
  {
    id: '6',
    name: 'Peter Ochieng',
    avatar: 'P',
    online: false,
    lastMessage: 'Thanks for the purchase! Enjoy your new gear.',
    timestamp: 'Yesterday',
    unread: 0,
    messages: [
      { id: '1', sender: 'user', text: 'Order received — thank you!', timestamp: 'Yesterday' },
      { id: '2', sender: 'other', text: 'Thanks for the purchase! Enjoy your new gear.', timestamp: 'Yesterday' },
    ],
  },
  {
    id: '7',
    name: 'Mary Wanjiku',
    avatar: 'M',
    online: false,
    lastMessage: 'Is the price negotiable? I am in Westlands.',
    timestamp: 'Mon',
    unread: 0,
    messages: [
      { id: '1', sender: 'other', text: 'Is the price negotiable? I am in Westlands.', timestamp: 'Mon' },
    ],
  },
  {
    id: '8',
    name: 'David Kimani',
    avatar: 'D',
    online: true,
    lastMessage: 'Can you send more photos of the laptop?',
    timestamp: 'Sat',
    unread: 1,
    messages: [
      { id: '1', sender: 'other', text: 'Can you send more photos of the laptop?', timestamp: 'Sat' },
    ],
  },
];

export const feedItems: FeedItem[] = [
  {
    id: '1',
    type: 'short',
    seller: '@SneakerHead_KE',
    avatar: 'S',
    description: 'These are fire! 🔥 #AOS #Fashion',
    sound: 'Original Sound - SneakerHead_KE',
    likes: 23500,
    comments: 542,
    productName: 'Sneakers Ditch',
    productPrice: 'KES 2,000',
  },
  {
    id: '2',
    type: 'short',
    seller: '@FashionHub254',
    avatar: 'F',
    description: 'New summer collection just dropped! ☀️ #Summer #AOS',
    sound: 'Trending Beat - DJ Mix',
    likes: 15200,
    comments: 328,
    productName: 'Summer Dress',
    productPrice: 'KES 3,500',
  },
  {
    id: '3',
    type: 'live',
    seller: '@TechDeals_KE',
    avatar: 'T',
    description: 'Flash sale on electronics! Ask me anything 📱',
    likes: 8900,
    comments: 1203,
    viewers: 1200,
    productName: 'iPhone 15 Pro',
    productPrice: 'KES 145,000',
  },
  {
    id: '4',
    type: 'short',
    seller: '@HomeDecor_NBI',
    avatar: 'H',
    description: 'Transform your space! 🏠 #Interior #AOS #HomeDecor',
    sound: 'Chill Vibes - LoFi',
    likes: 5600,
    comments: 189,
    productName: 'Modern Lamp Set',
    productPrice: 'KES 8,500',
  },
];

export const bannerSlides = [
  {
    id: 1,
    title: 'Mega Sale',
    subtitle: 'Up to 50% Off',
    description: 'Amazing deals on electronics, fashion & more',
    gradient: 'from-red-600 to-orange-500',
    icon: 'Zap',
  },
  {
    id: 2,
    title: 'Secure Payments',
    subtitle: 'Safe & Protected',
    description: 'Pay safely with buyer protection on every order',
    gradient: 'from-blue-600 to-blue-400',
    icon: 'Shield',
  },
  {
    id: 3,
    title: 'Sell Fast',
    subtitle: 'Post Your Items',
    description: 'Reach millions of buyers across Africa',
    gradient: 'from-green-600 to-green-400',
    icon: 'TrendingUp',
  },
];
